import { DEFAULT_RUNTIME_IMAGE_EXAMPLE } from '../../../lib/runtime-image-defaults.js';

export const ORCHESTRATOR_DEFAULT_RUNTIME_IMAGE = DEFAULT_RUNTIME_IMAGE_EXAMPLE;
export const ORCHESTRATOR_DEFAULT_CPU_LIMIT = '2';
export const ORCHESTRATOR_DEFAULT_MEMORY_LIMIT = '256m';
