import type { FieldDefinition } from './runtime-defaults.types.js';
import {
  DEFAULT_RUNTIME_IMAGE_EXAMPLE,
  RUNTIME_IMAGE_BOOTSTRAP_COPY,
} from '../../runtime-config-shared/runtime-image-defaults.js';
import {
  BASE_SECTION_DEFINITIONS,
  BOOLEAN_OPTIONS,
  ORCHESTRATOR_CONTEXT_STRATEGY_OPTIONS,
  ORCHESTRATOR_LOOP_MODE_OPTIONS,
  PULL_POLICY_OPTIONS,
  SPECIALIST_CONTEXT_STRATEGY_OPTIONS,
} from './runtime-defaults.schema.shared.js';

export {
  BASE_SECTION_DEFINITIONS,
  BOOLEAN_OPTIONS,
  ORCHESTRATOR_CONTEXT_STRATEGY_OPTIONS,
  ORCHESTRATOR_LOOP_MODE_OPTIONS,
  PULL_POLICY_OPTIONS,
  SPECIALIST_CONTEXT_STRATEGY_OPTIONS,
};

export const BASE_FIELD_DEFINITIONS: FieldDefinition[] = [
  {
    key: 'specialist_runtime_default_image',
    label: 'Image',
    description:
      `Image used for short-lived specialist agents. ${RUNTIME_IMAGE_BOOTSTRAP_COPY}`,
    configType: 'string',
    placeholder: DEFAULT_RUNTIME_IMAGE_EXAMPLE,
    section: 'runtime_containers',
  },
  {
    key: 'specialist_runtime_default_cpu',
    label: 'CPU',
    description: 'CPU allocation per specialist agent.',
    configType: 'string',
    placeholder: '2',
    section: 'runtime_containers',
  },
  {
    key: 'specialist_runtime_default_memory',
    label: 'Memory',
    description: 'Memory allocation per specialist agent, for example 256m or 1Gi.',
    configType: 'string',
    placeholder: '256m',
    section: 'runtime_containers',
  },
  {
    key: 'specialist_runtime_default_pull_policy',
    label: 'Pull policy',
    description: 'When specialist agent images should be pulled from the registry.',
    configType: 'string',
    placeholder: 'if-not-present',
    section: 'runtime_containers',
    options: PULL_POLICY_OPTIONS,
  },
  {
    key: 'agent.history_max_messages',
    label: 'History budget (messages)',
    description: 'Maximum message history kept before specialist task context is compacted.',
    configType: 'number',
    placeholder: '150',
    section: 'agent_context',
    inputMode: 'numeric',
    min: 1,
    step: 1,
  },
  {
    key: 'agent.history_preserve_recent',
    label: 'Base preserved recent messages',
    description:
      'Shared fallback tail preserved during compaction when a specialist or orchestrator-specific override is not set.',
    configType: 'number',
    placeholder: '30',
    section: 'agent_context',
    inputMode: 'numeric',
    min: 1,
    step: 1,
  },
  {
    key: 'agent.context_compaction_threshold',
    label: 'Base compaction threshold',
    description:
      'Shared fallback threshold used when a role-specific compaction threshold is not set.',
    configType: 'number',
    placeholder: '0.8',
    section: 'agent_context',
    inputMode: 'decimal',
    min: 0,
    max: 1,
    step: 0.01,
  },
  {
    key: 'agent.context_compaction_chars_per_token',
    label: 'Characters per token estimate',
    description: 'Fallback estimate used when model-side token accounting is unavailable.',
    configType: 'number',
    placeholder: '4',
    defaultValue: '4',
    section: 'agent_context',
    inputMode: 'numeric',
    min: 1,
    step: 1,
  },
  {
    key: 'agent.specialist_context_strategy',
    label: 'Specialist context strategy',
    description:
      'Default specialist continuity strategy. Auto prefers semantic handling and can adopt provider-native compaction when the active specialist agent path explicitly supports it.',
    configType: 'string',
    placeholder: 'auto',
    section: 'agent_context',
    options: SPECIALIST_CONTEXT_STRATEGY_OPTIONS,
  },
  {
    key: 'agent.specialist_context_warning_threshold',
    label: 'Specialist warning threshold',
    description: 'Warn specialists about rising context pressure before compaction starts.',
    configType: 'number',
    placeholder: '0.7',
    section: 'agent_context',
    inputMode: 'decimal',
    min: 0,
    max: 1,
    step: 0.01,
  },
  {
    key: 'agent.specialist_context_compaction_threshold',
    label: 'Specialist compaction threshold override',
    description: 'Role-specific compaction threshold used for specialist continuity handling.',
    configType: 'number',
    placeholder: '0.8',
    section: 'agent_context',
    inputMode: 'decimal',
    min: 0,
    max: 1,
    step: 0.01,
  },
  {
    key: 'agent.specialist_context_tail_messages',
    label: 'Specialist preserved tail',
    description:
      'Role-specific preserved recent message count used for specialist continuity handling.',
    configType: 'number',
    placeholder: '30',
    section: 'agent_context',
    inputMode: 'numeric',
    min: 1,
    step: 1,
  },
  {
    key: 'agent.specialist_context_preserve_memory_ops',
    label: 'Preserve recent memory ops',
    description: 'How many recent specialist memory breadcrumbs must survive compaction.',
    configType: 'number',
    placeholder: '2',
    defaultValue: '3',
    section: 'agent_context',
    inputMode: 'numeric',
    min: 0,
    step: 1,
  },
  {
    key: 'agent.specialist_context_preserve_artifact_ops',
    label: 'Preserve recent artifact ops',
    description: 'How many recent specialist artifact breadcrumbs must survive compaction.',
    configType: 'number',
    placeholder: '2',
    defaultValue: '3',
    section: 'agent_context',
    inputMode: 'numeric',
    min: 0,
    step: 1,
  },
  {
    key: 'agent.specialist_prepare_for_compaction_enabled',
    label: 'Run specialist pre-compaction prepare',
    description:
      'Ask specialists to checkpoint durable memory and transient continuity before compaction.',
    configType: 'boolean',
    placeholder: 'true',
    section: 'agent_context',
    options: BOOLEAN_OPTIONS,
  },
  {
    key: 'agent.orchestrator_loop_mode',
    label: 'Orchestrator loop mode',
    description:
      'Default loop mode for orchestrator activations. Reactive is preferred for frontier models; TPAOV can fit less capable models when a stricter step-by-step loop works better.',
    configType: 'string',
    placeholder: 'reactive',
    section: 'orchestrator_context',
    options: ORCHESTRATOR_LOOP_MODE_OPTIONS,
  },
  {
    key: 'agent.orchestrator_history_preserve_recent',
    label: 'Orchestrator preserved recent messages',
    description: 'Emergency-only preserved tail for unusually long orchestrator activations.',
    configType: 'number',
    placeholder: '30',
    section: 'orchestrator_context',
    inputMode: 'numeric',
    min: 0,
    step: 1,
  },
  {
    key: 'agent.orchestrator_context_compaction_threshold',
    label: 'Legacy orchestrator compaction threshold',
    description:
      'Compatibility threshold for emergency orchestrator compaction. Prefer the explicit orchestrator strategy and emergency threshold below.',
    configType: 'number',
    placeholder: '0.9',
    section: 'orchestrator_context',
    inputMode: 'decimal',
    min: 0,
    max: 1,
    step: 0.01,
  },
  {
    key: 'agent.orchestrator_context_strategy',
    label: 'Orchestrator context strategy',
    description:
      'Default orchestrator continuity strategy. Activation checkpoint is recommended because orchestrators run short activations and resume from persisted state.',
    configType: 'string',
    placeholder: 'activation_checkpoint',
    section: 'orchestrator_context',
    options: ORCHESTRATOR_CONTEXT_STRATEGY_OPTIONS,
  },
  {
    key: 'agent.orchestrator_finish_checkpoint_enabled',
    label: 'Persist activation finish checkpoint',
    description: 'Persist an orchestrator activation checkpoint before the activation exits.',
    configType: 'boolean',
    placeholder: 'true',
    section: 'orchestrator_context',
    options: BOOLEAN_OPTIONS,
  },
  {
    key: 'agent.orchestrator_finish_refresh_context_bundle',
    label: 'Refresh context bundle on finish',
    description:
      'Refresh attached context files after orchestrator finish persistence so the current activation can inspect the stored checkpoint and memory index.',
    configType: 'boolean',
    placeholder: 'true',
    section: 'orchestrator_context',
    options: BOOLEAN_OPTIONS,
  },
  {
    key: 'agent.orchestrator_emergency_compaction_threshold',
    label: 'Orchestrator emergency compaction threshold',
    description:
      'Only used when an orchestrator activation runs abnormally long and needs emergency compaction.',
    configType: 'number',
    placeholder: '0.95',
    section: 'orchestrator_context',
    inputMode: 'decimal',
    min: 0,
    max: 1,
    step: 0.01,
  },
  {
    key: 'agent.orchestrator_preserve_memory_ops',
    label: 'Orchestrator preserved memory ops',
    description:
      'How many recent orchestrator memory breadcrumbs should survive emergency compaction.',
    configType: 'number',
    placeholder: '2',
    section: 'orchestrator_context',
    inputMode: 'numeric',
    min: 0,
    step: 1,
  },
  {
    key: 'agent.orchestrator_preserve_artifact_ops',
    label: 'Orchestrator preserved artifact ops',
    description:
      'How many recent orchestrator artifact breadcrumbs should survive emergency compaction.',
    configType: 'number',
    placeholder: '2',
    section: 'orchestrator_context',
    inputMode: 'numeric',
    min: 0,
    step: 1,
  },
  {
    key: 'agent.loop_detection_repeat',
    label: 'Loop detection repeat count',
    description: 'Flag repeated loop patterns after this many repeated turns.',
    configType: 'number',
    placeholder: '3',
    section: 'agent_safeguards',
    inputMode: 'numeric',
    min: 1,
    step: 1,
  },
  {
    key: 'agent.response_repeat_threshold',
    label: 'Repeated response threshold',
    description: 'Mark the agent as stuck after this many repeated near-identical replies.',
    configType: 'number',
    placeholder: '2',
    section: 'agent_safeguards',
    inputMode: 'numeric',
    min: 1,
    step: 1,
  },
  {
    key: 'agent.no_file_change_threshold',
    label: 'No-progress intervention threshold',
    description:
      'Intervene only after this many turns with no meaningful progress toward task completion.',
    configType: 'number',
    placeholder: '50',
    section: 'agent_safeguards',
    inputMode: 'numeric',
    min: 1,
    step: 1,
  },
  {
    key: 'agent.max_tool_steps_per_burst',
    label: 'Maximum tool steps per burst',
    description:
      'How many tool steps a reactive loop may execute before it must stop and re-evaluate progress.',
    configType: 'number',
    placeholder: '12',
    section: 'agent_safeguards',
    inputMode: 'numeric',
    min: 1,
    step: 1,
  },
  {
    key: 'agent.max_mutating_steps_per_burst',
    label: 'Maximum mutating steps per burst',
    description:
      'How many mutating tool steps a reactive loop may execute before it must stop and re-evaluate progress.',
    configType: 'number',
    placeholder: '5',
    section: 'agent_safeguards',
    inputMode: 'numeric',
    min: 1,
    step: 1,
  },
  {
    key: 'agent.max_burst_elapsed_ms',
    label: 'Maximum burst elapsed time (ms)',
    description:
      'How long a reactive burst may run before the specialist agent forces a new planning boundary.',
    configType: 'number',
    placeholder: '120000',
    section: 'agent_safeguards',
    inputMode: 'numeric',
    min: 1,
    step: 1,
  },
  {
    key: 'agent.max_parallel_tool_calls_per_burst',
    label: 'Maximum parallel tool calls per burst',
    description:
      'How many read-only tool calls a reactive burst may execute in parallel before the specialist agent throttles concurrency.',
    configType: 'number',
    placeholder: '8',
    section: 'agent_safeguards',
    inputMode: 'numeric',
    min: 1,
    step: 1,
  },
  {
    key: 'agent.max_stuck_interventions',
    label: 'Maximum stuck interventions',
    description:
      'How many automatic recovery interventions the specialist agent attempts before failing the task.',
    configType: 'number',
    placeholder: '2',
    section: 'agent_safeguards',
    inputMode: 'numeric',
    min: 0,
    step: 1,
  },
  {
    key: 'agent.max_iterations',
    label: 'Maximum task iterations',
    description: 'Hard stop on agent loop iterations for a single task.',
    configType: 'number',
    placeholder: '800',
    section: 'task_limits',
    inputMode: 'numeric',
    min: 1,
    step: 1,
  },
  {
    key: 'agent.llm_max_retries',
    label: 'LLM retry attempts',
    description: 'Maximum retries for failed model calls before the task errors.',
    configType: 'number',
    placeholder: '5',
    section: 'agent_safeguards',
    inputMode: 'numeric',
    min: 1,
    step: 1,
  },
  {
    key: 'global_max_specialists',
    label: 'Max active specialists',
    description:
      'Maximum concurrent specialist tasks. Each active specialist consumes one specialist agent and one specialist execution.',
    configType: 'number',
    placeholder: '20',
    section: 'task_limits',
    inputMode: 'numeric',
    min: 1,
    step: 1,
  },
];
