import type pg from 'pg';

import type { ApiKeyIdentity } from './auth/api-key.js';
import type { AppEnv } from './config/schema.js';
import type { LogLevelCache } from './logging/execution/log-level-cache.js';
import type { LogService } from './logging/log-service.js';
import type { LogStreamService } from './logging/log-stream-service.js';
import type { ApiKeyService } from './services/api-key-service.js';
import type { AgenticSettingsService } from './services/agentic-settings-service.js';
import type { EventStreamService } from './services/event/event-stream-service.js';
import type { EventService } from './services/event/event-service.js';
import type { ExecutionEnvironmentCatalogService } from './services/execution-environment/catalog-service.js';
import type { ExecutionEnvironmentService } from './services/execution-environment/service.js';
import type { ExecutionEnvironmentVerificationService } from './services/execution-environment/verification-service.js';
import type { FleetService } from './services/fleet-service/fleet-service.js';
import type { GovernanceService } from './services/governance-service.js';
import type { ModelCatalogService } from './services/model-catalog/model-catalog-service.js';
import type { MissionControlHistoryService } from './services/workflow-operations/mission-control-history-service.js';
import type { MissionControlLiveService } from './services/workflow-operations/mission-control-live-service.js';
import type { MissionControlRecentService } from './services/workflow-operations/mission-control-recent-service.js';
import type { WorkflowDeliverablesService } from './services/workflow-operations/workflow-deliverables-service.js';
import type { WorkflowHistoryService } from './services/workflow-operations/workflow-history-service.js';
import type { WorkflowLiveConsoleService } from './services/workflow-operations/workflow-live-console-service.js';
import type { WorkflowOperationsStreamService } from './services/workflow-operations/workflow-operations-stream-service.js';
import type { WorkflowRailService } from './services/workflow-operations/workflow-rail-service.js';
import type { WorkflowWorkspaceService } from './services/workflow-operations/workflow-workspace-service.js';
import type { ContainerInventoryService } from './services/execution-environment/container-inventory-service.js';
import type { WorkspaceService } from './services/workspace/workspace-service.js';
import type { WorkspaceArtifactFileService } from './services/workspace/artifacts/workspace-artifact-file-service.js';
import type { PlaybookService } from './services/playbook/playbook-service.js';
import type { RoleDefinitionService } from './services/role-definition/role-definition-service.js';
import type { RuntimeDefaultsService } from './services/runtime-defaults/runtime-defaults-service.js';
import type { TaskService } from './services/task/task-service.js';
import type { UserService } from './services/user-service.js';
import type { WorkerConnectionHub } from './services/workers/worker-connection-hub.js';
import type { WorkerService } from './services/workers/worker-service.js';
import type { AcpSessionService } from './services/acp-session-service.js';
import type { AgentService } from './services/agent-service.js';
import type { OAuthService } from './services/oauth/oauth-service.js';
import type { OrchestratorConfigService } from './services/orchestrator/orchestrator-config-service.js';
import type { OrchestratorGrantService } from './services/orchestrator/orchestrator-grant-service.js';
import type { RemoteMcpOAuthClientProfileService } from './services/remote-mcp/oauth/remote-mcp-oauth-client-profile-service.js';
import type { RemoteMcpServerService } from './services/remote-mcp/servers/remote-mcp-server-service.js';
import type { RemoteMcpOAuthService } from './services/remote-mcp/oauth/remote-mcp-oauth-service.js';
import type { RemoteMcpVerificationService } from './services/remote-mcp/verification/remote-mcp-verification-service.js';
import type { SpecialistSkillService } from './services/specialist/specialist-skill-service.js';
import type { ToolTagService } from './services/tool-tag-service.js';
import type { CommunityCatalogSourceService } from './services/community-catalog/community-catalog-source.js';
import type { CommunityCatalogPreviewService } from './services/community-catalog/community-catalog-preview-service.js';
import type { CommunityCatalogImportService } from './services/community-catalog/community-catalog-import-service.js';
import type { CommunityCatalogOriginService } from './services/community-catalog/community-catalog-origin-service.js';
import type { WorkflowService } from './services/workflow-service/workflow-service.js';
import type { WorkflowActivationService } from './services/workflow-activation/workflow-activation-service.js';
import type { WorkflowDeliverableService } from './services/workflow-deliverables/workflow-deliverable-service.js';
import type { WorkflowInputPacketService } from './services/workflow-operations/workflow-input-packet-service.js';
import type { WorkflowInterventionService } from './services/workflow-operations/workflow-intervention-service.js';
import type { WorkflowOperatorBriefService } from './services/workflow-operator/workflow-operator-brief-service.js';
import type { WorkflowOperatorUpdateService } from './services/workflow-operator/workflow-operator-update-service.js';
import type { WorkflowRedriveService } from './services/workflow-service/workflow-redrive-service.js';
import type { WorkflowSettingsService } from './services/workflow-operations/workflow-settings-service.js';
import type { WorkflowSteeringSessionService } from './services/workflow-steering-session-service/workflow-steering-session-service.js';
import type { PlatformTransportTimingDefaults } from './services/platform-config/platform-timing-defaults.js';

declare module 'fastify' {
  interface FastifyInstance {
    config: AppEnv & PlatformTransportTimingDefaults;
    pgPool: pg.Pool;
    logService: LogService;
    logLevelCache: LogLevelCache;
    logStreamService: LogStreamService;
    eventService: EventService;
    eventStreamService: EventStreamService;
    containerInventoryService: ContainerInventoryService;
    workerConnectionHub: WorkerConnectionHub;
    workerService: WorkerService;
    governanceService: GovernanceService;
    workspaceService: WorkspaceService;
    workspaceArtifactFileService: WorkspaceArtifactFileService;
    playbookService: PlaybookService;
    workflowService: WorkflowService;
    workflowActivationService: WorkflowActivationService;
    workflowInputPacketService: WorkflowInputPacketService;
    workflowOperatorBriefService: WorkflowOperatorBriefService;
    workflowOperatorUpdateService: WorkflowOperatorUpdateService;
    workflowDeliverableService: WorkflowDeliverableService;
    workflowInterventionService: WorkflowInterventionService;
    workflowRedriveService: WorkflowRedriveService;
    workflowSettingsService: WorkflowSettingsService;
    workflowSteeringSessionService: WorkflowSteeringSessionService;
    taskService: TaskService;
    userService: UserService;
    apiKeyService: ApiKeyService;
    roleDefinitionService: RoleDefinitionService;
    runtimeDefaultsService: RuntimeDefaultsService;
    executionEnvironmentCatalogService: ExecutionEnvironmentCatalogService;
    executionEnvironmentService: ExecutionEnvironmentService;
    executionEnvironmentVerificationService: ExecutionEnvironmentVerificationService;
    fleetService: FleetService;
    modelCatalogService: ModelCatalogService;
    agenticSettingsService: AgenticSettingsService;
    workflowOperationsLiveService: MissionControlLiveService;
    workflowOperationsRecentService: MissionControlRecentService;
    workflowOperationsHistoryService: MissionControlHistoryService;
    workflowOperationsWorkspaceService: WorkflowWorkspaceService;
    workflowOperationsRailService: WorkflowRailService;
    workflowOperationsLiveConsoleService: WorkflowLiveConsoleService;
    workflowOperationsHistoryPacketService: WorkflowHistoryService;
    workflowOperationsDeliverablesService: WorkflowDeliverablesService;
    workflowOperationsStreamService: WorkflowOperationsStreamService;
    oauthService: OAuthService;
    remoteMcpOAuthClientProfileService: RemoteMcpOAuthClientProfileService;
    remoteMcpServerService: RemoteMcpServerService;
    remoteMcpOAuthService: RemoteMcpOAuthService;
    remoteMcpVerificationService: RemoteMcpVerificationService;
    specialistSkillService: SpecialistSkillService;
    communityCatalogSourceService: CommunityCatalogSourceService;
    communityCatalogPreviewService: CommunityCatalogPreviewService;
    communityCatalogImportService: CommunityCatalogImportService;
    communityCatalogOriginService: CommunityCatalogOriginService;
    orchestratorConfigService: OrchestratorConfigService;
    orchestratorGrantService: OrchestratorGrantService;
    acpSessionService: AcpSessionService;
    toolTagService: ToolTagService;
    agentService: AgentService;
  }

  interface FastifyRequest {
    auth?: ApiKeyIdentity;
    rawBody?: Buffer;
  }
}
