import { describe, expect, it } from 'vitest';

import {
  buildExecutionEnvironmentPayload,
  buildExecutionEnvironmentStats,
  createExecutionEnvironmentForm,
  sortExecutionEnvironments,
} from './execution-environments-page.support.js';

describe('execution environments page support', () => {
  it('creates trimmed payloads for custom environments', () => {
    expect(
      buildExecutionEnvironmentPayload({
        name: ' Ubuntu 24.04 / Go ',
        description: ' Curated apt-based environment ',
        image: ' ubuntu:24.04 ',
        cpu: ' 2 ',
        memory: ' 4Gi ',
        pullPolicy: 'always',
        operatorNotes: ' keep git and grep available ',
      }),
    ).toEqual({
      name: 'Ubuntu 24.04 / Go',
      description: 'Curated apt-based environment',
      image: 'ubuntu:24.04',
      cpu: '2',
      memory: '4Gi',
      pullPolicy: 'always',
      operatorNotes: 'keep git and grep available',
    });
  });

  it('prefills edit forms from an existing environment record', () => {
    expect(
      createExecutionEnvironmentForm({
        id: 'environment-1',
        name: 'Debian Base',
        description: 'Curated Debian baseline',
        image: 'debian:trixie-slim',
        cpu: '2',
        memory: '1Gi',
        pull_policy: 'if-not-present',
        operator_notes: 'baseline',
        bootstrap_commands: [],
        bootstrap_required_domains: [],
        declared_metadata: {},
        verified_metadata: {},
        tool_capabilities: {},
        compatibility_status: 'compatible',
        compatibility_errors: [],
        is_default: true,
        is_archived: false,
        is_claimable: true,
        usage_count: 4,
        source_kind: 'catalog',
        agent_hint: 'Execution environment: Debian Base',
      }),
    ).toEqual({
      name: 'Debian Base',
      description: 'Curated Debian baseline',
      image: 'debian:trixie-slim',
      cpu: '2',
      memory: '1Gi',
      pullPolicy: 'if-not-present',
      operatorNotes: 'baseline',
    });
  });

  it('sorts default and active environments ahead of archived entries', () => {
    expect(
      sortExecutionEnvironments([
        {
          id: 'environment-3',
          name: 'Ubuntu',
          image: 'ubuntu:24.04',
          cpu: '2',
          memory: '2Gi',
          pull_policy: 'if-not-present',
          bootstrap_commands: [],
          bootstrap_required_domains: [],
          declared_metadata: {},
          verified_metadata: {},
          tool_capabilities: {},
          compatibility_status: 'compatible',
          compatibility_errors: [],
          is_default: false,
          is_archived: true,
          is_claimable: false,
          usage_count: 0,
          source_kind: 'custom',
          agent_hint: '',
        },
        {
          id: 'environment-2',
          name: 'Debian',
          image: 'debian:trixie-slim',
          cpu: '2',
          memory: '1Gi',
          pull_policy: 'if-not-present',
          bootstrap_commands: [],
          bootstrap_required_domains: [],
          declared_metadata: {},
          verified_metadata: {},
          tool_capabilities: {},
          compatibility_status: 'compatible',
          compatibility_errors: [],
          is_default: false,
          is_archived: false,
          is_claimable: true,
          usage_count: 2,
          source_kind: 'catalog',
          agent_hint: '',
        },
        {
          id: 'environment-1',
          name: 'Fedora',
          image: 'fedora:42',
          cpu: '2',
          memory: '2Gi',
          pull_policy: 'if-not-present',
          bootstrap_commands: [],
          bootstrap_required_domains: [],
          declared_metadata: {},
          verified_metadata: {},
          tool_capabilities: {},
          compatibility_status: 'compatible',
          compatibility_errors: [],
          is_default: true,
          is_archived: false,
          is_claimable: true,
          usage_count: 1,
          source_kind: 'catalog',
          agent_hint: '',
        },
      ]).map((environment) => environment.id),
    ).toEqual(['environment-1', 'environment-2', 'environment-3']);
  });

  it('builds environment totals for the overview cards', () => {
    expect(
      buildExecutionEnvironmentStats([
        {
          id: 'environment-1',
          name: 'Fedora',
          image: 'fedora:42',
          cpu: '2',
          memory: '2Gi',
          pull_policy: 'if-not-present',
          bootstrap_commands: [],
          bootstrap_required_domains: [],
          declared_metadata: {},
          verified_metadata: {},
          tool_capabilities: {},
          compatibility_status: 'compatible',
          compatibility_errors: [],
          is_default: true,
          is_archived: false,
          is_claimable: true,
          usage_count: 1,
          source_kind: 'catalog',
          agent_hint: '',
        },
        {
          id: 'environment-2',
          name: 'Custom',
          image: 'ghcr.io/customer/dev:1.2.3',
          cpu: '4',
          memory: '8Gi',
          pull_policy: 'never',
          bootstrap_commands: [],
          bootstrap_required_domains: [],
          declared_metadata: {},
          verified_metadata: {},
          tool_capabilities: {},
          compatibility_status: 'incompatible',
          compatibility_errors: ['grep missing'],
          is_default: false,
          is_archived: false,
          is_claimable: false,
          usage_count: 0,
          source_kind: 'custom',
          agent_hint: '',
        },
        {
          id: 'environment-3',
          name: 'Archived',
          image: 'ubuntu:24.04',
          cpu: '2',
          memory: '2Gi',
          pull_policy: 'if-not-present',
          bootstrap_commands: [],
          bootstrap_required_domains: [],
          declared_metadata: {},
          verified_metadata: {},
          tool_capabilities: {},
          compatibility_status: 'compatible',
          compatibility_errors: [],
          is_default: false,
          is_archived: true,
          is_claimable: false,
          usage_count: 0,
          source_kind: 'catalog',
          agent_hint: '',
        },
      ]),
    ).toEqual({
      total: 3,
      claimable: 1,
      archived: 1,
      catalog: 2,
      custom: 1,
    });
  });
});
