import type { FastifyInstance } from 'fastify';

import { agentRoutes } from '../api/routes/agents.routes.js';
import { agenticSettingsRoutes } from '../api/routes/platform-config/agentic-settings.routes.js';
import { a2aRoutes } from '../api/routes/a2a.routes.js';
import { acpRoutes } from '../api/routes/acp.routes.js';
import { approvalQueueRoutes } from '../api/routes/approval-queue.routes.js';
import { apiKeyRoutes } from '../api/routes/api-keys.routes.js';
import { authRoutes } from '../api/routes/auth.routes.js';
import { eventRoutes } from '../api/routes/events.routes.js';
import { executionEnvironmentRoutes } from '../api/routes/execution-environments.routes.js';
import { governanceRoutes } from '../api/routes/governance.routes.js';
import { healthRoutes } from '../api/routes/health.routes.js';
import { orchestratorGrantRoutes } from '../api/routes/orchestrator-grants.routes.js';
import { safetynetRoutes } from '../api/routes/safetynet.routes.js';
import { workflowRoutes } from '../api/routes/workflows.routes.js';
import { workflowActivationRoutes } from '../api/routes/workflow-activations.routes.js';
import { orchestratorConfigRoutes } from '../api/routes/orchestrator-config.routes.js';
import { platformInstructionRoutes } from '../api/routes/platform-config/platform-instructions.routes.js';
import { taskRoutes } from '../api/routes/tasks.routes.js';
import { taskArtifactRoutes } from '../api/routes/task-platform/artifacts.routes.js';
import { taskPlatformRoutes } from '../api/routes/task-platform/routes.js';
import { taskStreamRoutes } from '../api/routes/task-stream.routes.js';
import { toolRoutes } from '../api/routes/tools.routes.js';
import { webhookRoutes } from '../api/routes/webhooks.routes.js';
import { workerRoutes } from '../api/routes/workers.routes.js';
import { workspaceRoutes } from '../api/routes/workspaces.routes.js';
import { runtimeCustomizationRoutes } from '../api/routes/platform-config/runtime-customization.routes.js';
import { roleDefinitionRoutes } from '../api/routes/platform-config/role-definitions.routes.js';
import { llmConfigRoutes } from '../api/routes/platform-config/llm-config.routes.js';
import { runtimeDefaultsRoutes } from '../api/routes/platform-config/runtime-defaults.routes.js';
import { runtimeConfigRoutes } from '../api/routes/platform-config/runtime-config.routes.js';
import { executionLogRoutes } from '../api/routes/execution-logs.routes.js';
import { fleetRoutes } from '../api/routes/fleet.routes.js';
import { userRoutes } from '../api/routes/users.routes.js';
import { meteringRoutes } from '../api/routes/metering.routes.js';
import { workflowOperationsRoutes } from '../api/routes/workflow-operations.routes.js';
import { circuitBreakerRoutes } from '../api/routes/circuit-breaker.routes.js';
import { containerRoutes } from '../api/routes/containers.routes.js';
import { oauthRoutes } from '../api/routes/oauth.routes.js';
import { playbookRoutes } from '../api/routes/playbooks.routes.js';
import { orchestratorControlRoutes } from '../api/routes/orchestrator-control.routes.js';
import { remoteMcpServerRoutes } from '../api/routes/remote-mcp/servers.routes.js';
import { remoteMcpOAuthClientProfileRoutes } from '../api/routes/remote-mcp/oauth-client-profiles.routes.js';
import { specialistSkillRoutes } from '../api/routes/platform-config/specialist-skills.routes.js';

export async function registerRoutes(app: FastifyInstance): Promise<void> {
  await app.register(healthRoutes);
  await app.register(safetynetRoutes);
  await app.register(approvalQueueRoutes);
  await app.register(a2aRoutes);
  await app.register(acpRoutes);
  await app.register(authRoutes);
  await app.register(apiKeyRoutes);
  await app.register(governanceRoutes);
  await app.register(taskRoutes);
  await app.register(taskArtifactRoutes);
  await app.register(taskPlatformRoutes);
  await app.register(taskStreamRoutes);
  await app.register(toolRoutes);
  await app.register(agentRoutes);
  await app.register(agenticSettingsRoutes);
  await app.register(workerRoutes);
  await app.register(eventRoutes);
  await app.register(webhookRoutes);
  await app.register(orchestratorGrantRoutes);
  await app.register(orchestratorConfigRoutes);
  await app.register(platformInstructionRoutes);
  await app.register(playbookRoutes);
  await app.register(orchestratorControlRoutes);
  await app.register(workflowRoutes);
  await app.register(workflowActivationRoutes);
  await app.register(workspaceRoutes);
  await app.register(runtimeCustomizationRoutes);
  await app.register(roleDefinitionRoutes);
  await app.register(executionEnvironmentRoutes);
  await app.register(llmConfigRoutes);
  await app.register(runtimeDefaultsRoutes);
  await app.register(runtimeConfigRoutes);
  await app.register(fleetRoutes);
  await app.register(userRoutes);
  await app.register(meteringRoutes);
  await app.register(circuitBreakerRoutes);
  await app.register(containerRoutes);
  await app.register(workflowOperationsRoutes);
  await app.register(oauthRoutes);
  await app.register(remoteMcpOAuthClientProfileRoutes);
  await app.register(remoteMcpServerRoutes);
  await app.register(specialistSkillRoutes);
  await app.register(executionLogRoutes);
}
