import type { FastifyInstance } from 'fastify';

import { agentRoutes } from '../api/routes/agents.routes.js';
import { a2aRoutes } from '../api/routes/a2a.routes.js';
import { acpRoutes } from '../api/routes/acp.routes.js';
import { approvalQueueRoutes } from '../api/routes/approval-queue.routes.js';
import { apiKeyRoutes } from '../api/routes/api-keys.routes.js';
import { authRoutes } from '../api/routes/auth.routes.js';
import { eventRoutes } from '../api/routes/events.routes.js';
import { executeRoutes } from '../api/routes/execute.routes.js';
import { governanceRoutes } from '../api/routes/governance.routes.js';
import { healthRoutes } from '../api/routes/health.routes.js';
import { integrationRoutes } from '../api/routes/integrations.routes.js';
import { orchestratorGrantRoutes } from '../api/routes/orchestrator-grants.routes.js';
import { workflowRoutes } from '../api/routes/workflows.routes.js';
import { workflowActivationRoutes } from '../api/routes/workflow-activations.routes.js';
import { orchestratorConfigRoutes } from '../api/routes/orchestrator-config.routes.js';
import { platformInstructionRoutes } from '../api/routes/platform-instructions.routes.js';
import { taskRoutes } from '../api/routes/tasks.routes.js';
import { taskArtifactRoutes } from '../api/routes/task-artifacts.routes.js';
import { taskPlatformRoutes } from '../api/routes/task-platform.routes.js';
import { toolRoutes } from '../api/routes/tools.routes.js';
import { webhookRoutes } from '../api/routes/webhooks.routes.js';
import { workerRoutes } from '../api/routes/workers.routes.js';
import { projectRoutes } from '../api/routes/projects.routes.js';
import { runtimeCustomizationRoutes } from '../api/routes/runtime-customization.routes.js';
import { webhookWorkItemTriggerRoutes } from '../api/routes/webhook-work-item-triggers.routes.js';
import { roleDefinitionRoutes } from '../api/routes/role-definitions.routes.js';
import { llmConfigRoutes } from '../api/routes/llm-config.routes.js';
import { scheduledWorkItemTriggerRoutes } from '../api/routes/scheduled-work-item-triggers.routes.js';
import { runtimeDefaultsRoutes } from '../api/routes/runtime-defaults.routes.js';
import { runtimeConfigRoutes } from '../api/routes/runtime-config.routes.js';
import { executionLogRoutes } from '../api/routes/execution-logs.routes.js';
import { fleetRoutes } from '../api/routes/fleet.routes.js';
import { userRoutes } from '../api/routes/users.routes.js';
import { meteringRoutes } from '../api/routes/metering.routes.js';
import { circuitBreakerRoutes } from '../api/routes/circuit-breaker.routes.js';
import { oauthRoutes } from '../api/routes/oauth.routes.js';
import { playbookRoutes } from '../api/routes/playbooks.routes.js';
import { orchestratorControlRoutes } from '../api/routes/orchestrator-control.routes.js';

export async function registerRoutes(app: FastifyInstance): Promise<void> {
  await app.register(healthRoutes);
  await app.register(approvalQueueRoutes);
  await app.register(a2aRoutes);
  await app.register(acpRoutes);
  await app.register(authRoutes);
  await app.register(apiKeyRoutes);
  await app.register(governanceRoutes);
  await app.register(taskRoutes);
  await app.register(taskArtifactRoutes);
  await app.register(taskPlatformRoutes);
  await app.register(toolRoutes);
  await app.register(executeRoutes);
  await app.register(agentRoutes);
  await app.register(workerRoutes);
  await app.register(eventRoutes);
  await app.register(webhookRoutes);
  await app.register(integrationRoutes);
  await app.register(orchestratorGrantRoutes);
  await app.register(orchestratorConfigRoutes);
  await app.register(platformInstructionRoutes);
  await app.register(playbookRoutes);
  await app.register(orchestratorControlRoutes);
  await app.register(workflowRoutes);
  await app.register(workflowActivationRoutes);
  await app.register(projectRoutes);
  await app.register(runtimeCustomizationRoutes);
  await app.register(webhookWorkItemTriggerRoutes);
  await app.register(scheduledWorkItemTriggerRoutes);
  await app.register(roleDefinitionRoutes);
  await app.register(llmConfigRoutes);
  await app.register(runtimeDefaultsRoutes);
  await app.register(runtimeConfigRoutes);
  await app.register(fleetRoutes);
  await app.register(userRoutes);
  await app.register(meteringRoutes);
  await app.register(circuitBreakerRoutes);
  await app.register(oauthRoutes);
  await app.register(executionLogRoutes);
}
