import { createElement } from 'react';
import { renderToStaticMarkup } from 'react-dom/server';
import { describe, expect, it } from 'vitest';

import { WorkflowDeliverableTargetLink } from './workflow-deliverable-target-link.js';

describe('WorkflowDeliverableTargetLink', () => {
  it('renders workflow-context targets inline instead of linking to deprecated task or workflow pages', () => {
    const taskHtml = renderToStaticMarkup(
      createElement(WorkflowDeliverableTargetLink, {
        target: {
          target_kind: 'task',
          label: 'Generated by task',
          url: '/work/tasks/task-1',
        },
      }),
    );
    const workflowHtml = renderToStaticMarkup(
      createElement(WorkflowDeliverableTargetLink, {
        target: {
          target_kind: 'workflow',
          label: 'Workflow summary',
          url: '/workflows/workflow-1?tab=details',
        },
      }),
    );

    expect(taskHtml).toContain('Generated by task (Task)');
    expect(taskHtml).toContain('Already visible in this workflow workspace.');
    expect(taskHtml).not.toContain('href="/work/tasks/task-1"');
    expect(workflowHtml).toContain('Workflow summary (Workflow)');
    expect(workflowHtml).toContain('Already visible in this workflow workspace.');
    expect(workflowHtml).not.toContain('href="/workflows/workflow-1?tab=details"');
  });

  it('renders external artifact targets as one direct-open action after rewriting deprecated routes', () => {
    const html = renderToStaticMarkup(
      createElement(WorkflowDeliverableTargetLink, {
        target: {
          target_kind: 'artifact',
          label: 'Open artifact',
          url: 'http://localhost:3000/artifacts/tasks/task-1/artifact-1?return_to=%2Fworkflows%2Fworkflow-1',
          path: 'artifacts/release-bundle.zip',
          artifact_id: 'artifact-1',
        },
      }),
    );

    expect(html).toContain('Open artifact (Artifact)');
    expect(html).toContain('Open target');
    expect(html).toContain('/api/v1/tasks/task-1/artifacts/artifact-1/preview');
    expect(html).not.toContain('/artifacts/tasks/task-1/artifact-1');
    expect(html).not.toContain('return_to=');
    expect(html).not.toContain('target="_blank"');
  });

  it('renders deprecated workflow deliverable routes inline instead of linking to removed dashboard surfaces', () => {
    const html = renderToStaticMarkup(
      createElement(WorkflowDeliverableTargetLink, {
        target: {
          target_kind: 'artifact',
          label: 'Release bundle',
          url: '/workflows/workflow-1/deliverables/deliverable-1',
          path: 'artifacts/release-bundle.zip',
        },
      }),
    );

    expect(html).toContain('Release bundle');
    expect(html).toContain('Already visible in this workflow workspace.');
    expect(html).not.toContain('href="/workflows/workflow-1/deliverables/deliverable-1"');
    expect(html).not.toContain('Open artifact in new tab');
  });

  it('renders workflow file targets as direct links without preview-dialog affordances', () => {
    const html = renderToStaticMarkup(
      createElement(WorkflowDeliverableTargetLink, {
        target: {
          target_kind: 'input_packet_file',
          label: 'Launch packet',
          url:
            'http://localhost:3000/api/v1/workflows/workflow-1/input-packets/packet-1/files/file-1/content?return_to=%2Fworkflows%2Fworkflow-1',
        },
      }),
    );

    expect(html).toContain('Launch packet (Input Packet File)');
    expect(html).toContain('Open target');
    expect(html).toContain('/api/v1/workflows/workflow-1/input-packets/packet-1/files/file-1/content');
    expect(html).not.toContain('return_to=');
    expect(html).not.toContain('target="_blank"');
  });

  it('renders malformed direct targets without throwing', () => {
    const html = renderToStaticMarkup(
      createElement(WorkflowDeliverableTargetLink, {
        target: {} as never,
      }),
    );

    expect(html).toContain('Linked output');
    expect(html).toContain('Already visible in this workflow workspace.');
    expect(html).not.toContain('href=');
  });
});
