import { createElement } from 'react';
import { renderToStaticMarkup } from 'react-dom/server';
import { describe, expect, it } from 'vitest';

import { WorkflowDeliverableTargetLink } from './workflow-deliverable-target-link.js';

describe('WorkflowDeliverableTargetLink', () => {
  it('renders workflow-context targets inline instead of linking to deprecated task or workflow pages', () => {
    const taskHtml = renderToStaticMarkup(
      createElement(WorkflowDeliverableTargetLink, {
        target: {
          target_kind: 'task',
          label: 'Generated by task',
          url: '/work/tasks/task-1',
        },
      }),
    );
    const workflowHtml = renderToStaticMarkup(
      createElement(WorkflowDeliverableTargetLink, {
        target: {
          target_kind: 'workflow',
          label: 'Workflow summary',
          url: '/workflows/workflow-1?tab=details',
        },
      }),
    );

    expect(taskHtml).toContain('Generated by task (Task)');
    expect(taskHtml).toContain('Already visible in this workflow workspace.');
    expect(taskHtml).not.toContain('href="/work/tasks/task-1"');
    expect(workflowHtml).toContain('Workflow summary (Workflow)');
    expect(workflowHtml).toContain('Already visible in this workflow workspace.');
    expect(workflowHtml).not.toContain('href="/workflows/workflow-1?tab=details"');
  });

  it('rewrites deprecated artifact routes into preview-safe artifact actions', () => {
    const html = renderToStaticMarkup(
      createElement(WorkflowDeliverableTargetLink, {
        target: {
          target_kind: 'artifact',
          label: 'Open artifact',
          url: 'http://localhost:3000/artifacts/tasks/task-1/artifact-1?return_to=%2Fworkflows%2Fworkflow-1',
          path: 'artifacts/release-bundle.zip',
          artifact_id: 'artifact-1',
        },
        primary: true,
      }),
    );

    expect(html).toContain('Open artifact');
    expect(html).toContain('Preview inline');
    expect(html).toContain('Open artifact in new tab');
    expect(html).toContain('/api/v1/tasks/task-1/artifacts/artifact-1/preview');
    expect(html).not.toContain('/artifacts/tasks/task-1/artifact-1');
    expect(html).not.toContain('return_to=');
  });
});
