export const TASK_CONTEXT_SECRET_REDACTION = 'redacted://task-context-secret';
export const TASK_CONTEXT_LOG_VERSION = 1;
export const TASK_CONTEXT_MEMORY_INDEX_LIMIT = 100;
export const TASK_CONTEXT_ARTIFACT_INDEX_LIMIT = 100;
export const TASK_CONTEXT_RECENT_HANDOFF_LIMIT = 2;
export const DEFAULT_ASSEMBLED_PROMPT_WARNING_THRESHOLD_CHARS = 32_000;
export const UPSTREAM_OUTPUT_MAX_BYTES = 102400;
